// Melon specific translations
const melonTranslations = {
    'pt-BR': {
        'melon.title': 'Melão',
        'melon.subtitle': 'Fruta doce e aromática, com polpa suculenta e refrescante. Disponível em diversas variedades, cada uma com características únicas de sabor, textura e aparência.',
        'melon.seasonality.title': 'Sazonalidade',
        'melon.seasonality.high': 'Alta Disponibilidade',
        'melon.seasonality.medium': 'Média Disponibilidade',
        'melon.seasonality.low': 'Baixa Disponibilidade',
        'melon.regions.title': 'Nossos Parceiros Produtores pelo Brasil',
        'melon.regions.rn': 'Maior estado produtor de melão do Brasil, com destaque para a região de Mossoró',
        'melon.regions.rn.title': 'Rio Grande do Norte',
        'melon.regions.rn.description': 'Principal polo de produção e exportação de melão do Brasil, favorecido por alta luminosidade, baixa umidade relativa e água subterrânea de qualidade, garantindo frutos doces e saudáveis.',
        'melon.regions.mossoro.title': 'Mossoró - RN',
        'melon.regions.mossoro.description': 'Capital nacional do melão, liderando as exportações brasileiras com tecnologia de ponta e certificações internacionais.',
        'melon.varieties.title': 'Variedades',
        'melon.varieties.amarelo.title': 'Melão Amarelo',
        'melon.varieties.amarelo.description': 'Variedade tradicional brasileira com polpa doce e aromática. Casca amarela característica e formato oval. Ideal para consumo <em>in natura</em> e exportação.',
        'melon.varieties.amarelo.period': 'Agosto - Março',
        'melon.varieties.cantaloupe.title': 'Melão Cantaloupe',
        'melon.varieties.cantaloupe.description': 'Melão premium com polpa alaranjada intensa e aroma marcante. Casca reticulada e textura cremosa. Muito apreciado no mercado internacional.',
        'melon.varieties.cantaloupe.period': 'Agosto - Janeiro',
        'melon.varieties.galia.title': 'Melão Galia',
        'melon.varieties.galia.description': 'Variedade originária de Israel com casca reticulada dourada. Polpa verde-clara, extremamente doce e suculenta. Excelente para mercados exigentes.',
        'melon.varieties.galia.period': 'Agosto - Abril',
        'melon.varieties.sapo.title': 'Melão Pele-de-sapo',
        'melon.varieties.sapo.description': 'Melão espanhol de grande porte com casca verde mosqueada. Polpa branca cristalina, muito doce e refrescante. Longa durabilidade pós-colheita.',
        'melon.varieties.sapo.period': 'Agosto - Março',
        'melon.commercialization.title': 'Comercialização',
        'melon.commercialization.packaging.title': 'Embalagem',
        'melon.commercialization.packaging.net': 'Peso Líquido:',
        'melon.commercialization.packaging.gross': 'Peso Bruto:',
        'melon.commercialization.pallet.title': 'Pallet',
        'melon.commercialization.pallet.boxes': 'Caixas por Pallet:',
        'melon.commercialization.calibers.title': 'Calibres',
        'melon.contact.title': 'Interessado em Melão?',
        'melon.contact.subtitle': 'Entre em contato conosco para mais informações sobre disponibilidade, preços e especificações técnicas.',
        'melon.contact.cta': 'Solicitar Cotação',
        'months.jan': 'Jan',
        'months.feb': 'Fev',
        'months.mar': 'Mar',
        'months.apr': 'Abr',
        'months.may': 'Mai',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Ago',
        'months.sep': 'Set',
        'months.oct': 'Out',
        'months.nov': 'Nov',
        'months.dec': 'Dez'
    },
    'en': {
        'melon.title': 'Melon',
        'melon.subtitle': 'Sweet and aromatic fruit with succulent and refreshing pulp. Available in various varieties, each with unique characteristics of flavor, texture and appearance.',
        'melon.seasonality.title': 'Seasonality',
        'melon.seasonality.high': 'High Availability',
        'melon.seasonality.medium': 'Medium Availability',
        'melon.seasonality.low': 'Low Availability',
        'melon.regions.title': 'Our Producer Partners Across Brazil',
        'melon.regions.rn': 'Largest melon producing state in Brazil, with emphasis on the Mossoró region',
        'melon.regions.rn.title': 'Rio Grande do Norte',
        'melon.regions.rn.description': 'Main melon production and export hub in Brazil, favored by high luminosity, low relative humidity and quality groundwater, ensuring sweet and healthy fruits.',
        'melon.regions.mossoro.title': 'Mossoró - RN',
        'melon.regions.mossoro.description': 'National capital of melon, leading Brazilian exports with cutting-edge technology and international certifications.',
        'melon.varieties.title': 'Varieties',
        'melon.varieties.amarelo.title': 'Yellow Melon',
        'melon.varieties.amarelo.description': 'Traditional Brazilian variety with sweet and aromatic pulp. Characteristic yellow skin and oval shape. Ideal for fresh consumption and export.',
        'melon.varieties.amarelo.period': 'August - March',
        'melon.varieties.cantaloupe.title': 'Cantaloupe Melon',
        'melon.varieties.cantaloupe.description': 'Premium melon with intense orange pulp and distinctive aroma. Netted skin and creamy texture. Highly appreciated in international markets.',
        'melon.varieties.cantaloupe.period': 'August - January',
        'melon.varieties.galia.title': 'Galia Melon',
        'melon.varieties.galia.description': 'Variety originating from Israel with golden netted skin. Light green pulp, extremely sweet and juicy. Excellent for demanding markets.',
        'melon.varieties.galia.period': 'August - April',
        'melon.varieties.sapo.title': 'Piel de Sapo Melon',
        'melon.varieties.sapo.description': 'Large Spanish melon with mottled green skin. Crystalline white pulp, very sweet and refreshing. Long post-harvest durability.',
        'melon.varieties.sapo.period': 'August - March',
        'melon.commercialization.title': 'Commercialization',
        'melon.commercialization.packaging.title': 'Packaging',
        'melon.commercialization.packaging.net': 'Net Weight:',
        'melon.commercialization.packaging.gross': 'Gross Weight:',
        'melon.commercialization.pallet.title': 'Pallet',
        'melon.commercialization.pallet.boxes': 'Boxes per Pallet:',
        'melon.commercialization.calibers.title': 'Calibers',
        'melon.contact.title': 'Interested in Melon?',
        'melon.contact.subtitle': 'Contact us for more information about availability, prices and technical specifications.',
        'melon.contact.cta': 'Request Quote',
        'months.jan': 'Jan',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Apr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Aug',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dec'
    },
    'es': {
        'melon.title': 'Melón',
        'melon.subtitle': 'Fruta dulce y aromática con pulpa suculenta y refrescante. Disponible en diversas variedades, cada una con características únicas de sabor, textura y apariencia.',
        'melon.seasonality.title': 'Estacionalidad',
        'melon.seasonality.high': 'Alta Disponibilidad',
        'melon.regions.rn.title': 'Rio Grande do Norte',
        'melon.regions.rn.description': 'Principal polo de producción y exportación de melón de Brasil, favorecido por alta luminosidad, baja humedad relativa y agua subterránea de calidad, garantizando frutos dulces y saludables.',
        'melon.regions.mossoro.title': 'Mossoró - RN',
        'melon.regions.mossoro.description': 'Capital nacional del melón, liderando las exportaciones brasileñas con tecnología de punta y certificaciones internacionales.',
        'melon.seasonality.medium': 'Disponibilidad Media',
        'melon.seasonality.low': 'Baja Disponibilidad',
        'melon.regions.title': 'Nuestros Socios Productores por Brasil',
        'melon.regions.rn': 'Mayor estado productor de melón de Brasil, con destaque en la región de Mossoró',
        'melon.varieties.title': 'Variedades',
        'melon.varieties.amarelo.title': 'Melón Amarillo',
        'melon.varieties.amarelo.description': 'Variedad tradicional brasileña con pulpa dulce y aromática. Cáscara amarilla característica y forma ovalada. Ideal para consumo fresco y exportación.',
        'melon.varieties.amarelo.period': 'Agosto - Marzo',
        'melon.varieties.cantaloupe.title': 'Melón Cantaloupe',
        'melon.varieties.cantaloupe.description': 'Melón premium con pulpa anaranjada intensa y aroma distintivo. Cáscara reticulada y textura cremosa. Muy apreciado en mercados internacionales.',
        'melon.varieties.cantaloupe.period': 'Agosto - Enero',
        'melon.varieties.galia.title': 'Melón Galia',
        'melon.varieties.galia.description': 'Variedad originaria de Israel con cáscara reticulada dorada. Pulpa verde clara, extremadamente dulce y jugosa. Excelente para mercados exigentes.',
        'melon.varieties.galia.period': 'Agosto - Abril',
        'melon.varieties.sapo.title': 'Melón Piel de Sapo',
        'melon.varieties.sapo.description': 'Melón español de gran tamaño con cáscara verde moteada. Pulpa blanca cristalina, muy dulce y refrescante. Larga durabilidad postcosecha.',
        'melon.varieties.sapo.period': 'Agosto - Marzo',
        'melon.commercialization.title': 'Comercialización',
        'melon.commercialization.packaging.title': 'Embalaje',
        'melon.commercialization.packaging.net': 'Peso Neto:',
        'melon.commercialization.packaging.gross': 'Peso Bruto:',
        'melon.commercialization.pallet.title': 'Pallet',
        'melon.commercialization.pallet.boxes': 'Cajas por Pallet:',
        'melon.commercialization.calibers.title': 'Calibres',
        'melon.contact.title': '¿Interesado en Melón?',
        'melon.contact.subtitle': 'Contáctanos para más información sobre disponibilidad, precios y especificaciones técnicas.',
        'melon.contact.cta': 'Solicitar Cotización',
        'months.jan': 'Ene',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Abr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Ago',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dic'
    }
};

// Extend main translations with melon specific ones
if (typeof translations !== 'undefined') {
    Object.keys(melonTranslations).forEach(lang => {
        if (translations[lang]) {
            Object.assign(translations[lang], melonTranslations[lang]);
        }
    });
}

    
    // Inicializar ícones Lucide
    if (window.lucide && typeof window.lucide.createIcons === 'function') {
        window.lucide.createIcons();
    }
