// Watermelon specific translations
const watermelonTranslations = {
    'pt-BR': {
        'watermelon.title': 'Melancia',
        'watermelon.subtitle': 'Melancias premium selecionadas das melhores regiões produtoras do Brasil. Com polpa vermelha intensa, alto teor de água e doçura excepcional, nossas melancias atendem aos mais rigorosos padrões internacionais de exportação.',
        'watermelon.seasonality.title': 'Sazonalidade',
        'watermelon.seasonality.high': 'Alta Disponibilidade',
        'watermelon.seasonality.medium': 'Média Disponibilidade',
        'watermelon.regions.title': 'Nossos Parceiros Produtores pelo Brasil',
        'watermelon.regions.primary': 'Principais Produtores',
        'watermelon.regions.secondary': 'Boa Expressividade',
        'watermelon.regions.uruana': 'Berço da melanicultura irrigada brasileira desde 1968. Uruana transformou-se no maior polo tecnológico de melancia do país com produtividade de 45 ton/hectare.',
        'watermelon.regions.teixeira': 'Maior produtor nacional com 391.528 toneladas anuais. Teixeira de Freitas lidera a expansão com crescimento de 36,77% em área cultivada, combinando solos arenosos ideais e irrigação de ponta.',
        'watermelon.regions.rn': 'Segundo maior produtor com 283.640 toneladas anuais. Mossoró destaca-se pela qualidade premium e tecnologia de irrigação, beneficiada pelo clima semiárido que permite cultivo o ano todo.',
        'watermelon.regions.pe': 'Polo de inovação no semiárido com 97.975 toneladas anuais. Petrolina revolucionou o cultivo com técnicas da Embrapa, alcançando produtividades recordes de até 61 toneladas por hectare.',
        'watermelon.varieties.title': 'Variedades',
        'watermelon.varieties.seedless.title': 'Seedless',
        'watermelon.varieties.seedless.description': 'Melancias sem sementes, ideais para consumo direto e exportação premium.',
        'watermelon.varieties.seeded.title': 'Com Sementes',
        'watermelon.varieties.seeded.description': 'Variedades tradicionais com sementes, sabor intenso e alta durabilidade.',
        'watermelon.commercialization.title': 'Comercialização',
        'watermelon.commercialization.packaging.title': 'Embalagem',
        'watermelon.commercialization.packaging.net': 'Peso Líquido:',
        'watermelon.commercialization.packaging.gross': 'Peso Bruto:',
        'watermelon.commercialization.pallet.title': 'Pallet',
        'watermelon.commercialization.pallet.boxes': 'Caixas por Pallet:',
        'watermelon.commercialization.calibers.title': 'Calibres',
        'watermelon.contact.title': 'Interessado em Melancia?',
        'watermelon.contact.subtitle': 'Entre em contato conosco para mais informações sobre disponibilidade, preços e especificações técnicas.',
        'watermelon.contact.cta': 'Solicitar Cotação',
        'months.jan': 'Jan',
        'months.feb': 'Fev',
        'months.mar': 'Mar',
        'months.apr': 'Abr',
        'months.may': 'Mai',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Ago',
        'months.sep': 'Set',
        'months.oct': 'Out',
        'months.nov': 'Nov',
        'months.dec': 'Dez'
    },
    'en': {
        'watermelon.title': 'Watermelon',
        'watermelon.subtitle': 'Premium watermelons selected from Brazil\'s finest producing regions. With intense red pulp, high water content and exceptional sweetness, our watermelons meet the most rigorous international export standards.',
        'watermelon.seasonality.title': 'Seasonality',
        'watermelon.seasonality.high': 'High Availability',
        'watermelon.seasonality.medium': 'Medium Availability',
        'watermelon.regions.title': 'Our Producer Partners Across Brazil',
        'watermelon.regions.primary': 'Main Producers',
        'watermelon.regions.secondary': 'Good Expressiveness',
        'watermelon.regions.uruana': 'Birthplace of Brazilian irrigated watermelon farming since 1968. Uruana became the country\'s largest technological watermelon hub with 45 tons/hectare productivity.',
        'watermelon.regions.teixeira': 'Brazil\'s largest producer with 391,528 tons annually. Teixeira de Freitas leads expansion with 36.77% growth in cultivated area, combining ideal sandy soils and cutting-edge irrigation.',
        'watermelon.regions.rn': 'Second largest producer with 283,640 tons annually. Mossoró stands out for premium quality and irrigation technology, benefited by semi-arid climate allowing year-round cultivation.',
        'watermelon.regions.pe': 'Semi-arid innovation hub with 97,975 tons annually. Petrolina revolutionized cultivation with Embrapa techniques, achieving record productivities up to 61 tons per hectare.',
        'watermelon.varieties.title': 'Varieties',
        'watermelon.varieties.seedless.title': 'Seedless',
        'watermelon.varieties.seedless.description': 'Seedless watermelons, ideal for direct consumption and premium export.',
        'watermelon.varieties.seeded.title': 'Seeded',
        'watermelon.varieties.seeded.description': 'Traditional varieties with seeds, intense flavor and high durability.',
        'watermelon.commercialization.title': 'Commercialization',
        'watermelon.commercialization.packaging.title': 'Packaging',
        'watermelon.commercialization.packaging.net': 'Net Weight:',
        'watermelon.commercialization.packaging.gross': 'Gross Weight:',
        'watermelon.commercialization.pallet.title': 'Pallet',
        'watermelon.commercialization.pallet.boxes': 'Boxes per Pallet:',
        'watermelon.commercialization.calibers.title': 'Calibers',
        'watermelon.contact.title': 'Interested in Watermelon?',
        'watermelon.contact.subtitle': 'Contact us for more information about availability, prices and technical specifications.',
        'watermelon.contact.cta': 'Request Quote',
        'months.jan': 'Jan',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Apr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Aug',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dec'
    },
    'es': {
        'watermelon.title': 'Sandía',
        'watermelon.subtitle': 'Sandías premium seleccionadas de las mejores regiones productoras de Brasil. Con pulpa roja intensa, alto contenido de agua y dulzura excepcional, nuestras sandías cumplen los más rigurosos estándares internacionales de exportación.',
        'watermelon.seasonality.title': 'Estacionalidad',
        'watermelon.seasonality.high': 'Alta Disponibilidad',
        'watermelon.seasonality.medium': 'Disponibilidad Media',
        'watermelon.regions.title': 'Nuestros Socios Productores por Brasil',
        'watermelon.regions.primary': 'Principales Productores',
        'watermelon.regions.secondary': 'Buena Expresividad',
        'watermelon.regions.uruana': 'Cuna de la sandiacultura irrigada brasileña desde 1968. Uruana se transformó en el mayor polo tecnológico de sandía del país con productividad de 45 ton/hectárea.',
        'watermelon.regions.teixeira': 'Mayor productor nacional con 391.528 toneladas anuales. Teixeira de Freitas lidera la expansión con crecimiento del 36,77% en área cultivada, combinando suelos arenosos ideales e irrigación de punta.',
        'watermelon.regions.rn': 'Segundo mayor productor con 283.640 toneladas anuales. Mossoró se destaca por calidad premium y tecnología de irrigación, beneficiada por clima semiárido que permite cultivo todo el año.',
        'watermelon.regions.pe': 'Polo de innovación en el semiárido con 97.975 toneladas anuales. Petrolina revolucionó el cultivo con técnicas de Embrapa, alcanzando productividades récord de hasta 61 toneladas por hectárea.',
        'watermelon.varieties.title': 'Variedades',
        'watermelon.varieties.seedless.title': 'Sin Semillas',
        'watermelon.varieties.seedless.description': 'Sandías sin semillas, ideales para consumo directo y exportación premium.',
        'watermelon.varieties.seeded.title': 'Con Semillas',
        'watermelon.varieties.seeded.description': 'Variedades tradicionales con semillas, sabor intenso y alta durabilidad.',
        'watermelon.commercialization.title': 'Comercialización',
        'watermelon.commercialization.packaging.title': 'Embalaje',
        'watermelon.commercialization.packaging.net': 'Peso Neto:',
        'watermelon.commercialization.packaging.gross': 'Peso Bruto:',
        'watermelon.commercialization.pallet.title': 'Pallet',
        'watermelon.commercialization.pallet.boxes': 'Cajas por Pallet:',
        'watermelon.commercialization.calibers.title': 'Calibres',
        'watermelon.contact.title': '¿Interesado en Sandía?',
        'watermelon.contact.subtitle': 'Contáctenos para más información sobre disponibilidad, precios y especificaciones técnicas.',
        'watermelon.contact.cta': 'Solicitar Cotización',
        'months.jan': 'Ene',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Abr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Ago',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dic'
    }
};

// Extend main translations with watermelon specific ones
if (typeof translations !== 'undefined') {
    Object.keys(watermelonTranslations).forEach(lang => {
        if (translations[lang]) {
            Object.assign(translations[lang], watermelonTranslations[lang]);
        }
    });
}

    
    // Inicializar ícones Lucide
    if (window.lucide && typeof window.lucide.createIcons === 'function') {
        window.lucide.createIcons();
    }
});
