// Grape specific translations
const grapeTranslations = {
    'pt-BR': {
        'grape.title': 'Uva',
        'grape.subtitle': 'Uvas premium do Vale do São Francisco, reconhecidas pela qualidade internacional e sabor excepcional.',
        'grape.varieties.title': 'Variedades e Sazonalidade',
        'grape.varieties.intro': 'Cada variedade de uva possui características únicas e períodos de maior disponibilidade ao longo do ano:',
        'grape.varieties.lumiar.title': 'BRS 54 Lumiar - Sem semente',
        'grape.varieties.taina.title': 'BRS Tainá - Com semente',
        'grape.varieties.vitoria.title': 'BRS Vitória',
        'grape.varieties.magna.title': 'BRS Magna',
        'grape.varieties.iris.title': 'BRS Iris',
        'grape.varieties.melodia.title': 'BRS Melodia',
        'grape.varieties.weight': 'Peso do cacho:',
        'grape.varieties.brix': 'Brix:',
        'grape.varieties.type': 'Tipo:',
        'grape.varieties.white': 'Branca',
        'grape.varieties.black': 'Preta',
        'grape.varieties.red': 'Vermelha',
        'grape.regions.title': 'Principais Regiões Produtoras',
        'grape.regions.saofrancisco.title': 'Vale do São Francisco',
        'grape.regions.saofrancisco.description': 'Principal região produtora de uvas de mesa para exportação no Brasil, reconhecida internacionalmente pela qualidade superior e tecnologia de irrigação avançada.',
        'grape.regions.petrolina': 'Principal polo de fruticultura irrigada do Vale do São Francisco, reconhecido pela excelência na produção de uvas de mesa.',
        'grape.regions.juazeiro': 'Centro de inovação tecnológica na viticultura tropical, com tecnologia avançada de irrigação e manejo.',
        'grape.commercialization.title': 'Comercialização',
        'grape.commercialization.punnets.title': 'Punnets',
        'grape.commercialization.bags.title': 'Bags',
        'grape.commercialization.pallet.title': 'Pallet',
        'grape.commercialization.pallet.air': 'Aéreo:',
        'grape.commercialization.pallet.sea': 'Marítimo:',
        'grape.contact.title': 'Interessado em Uva?',
        'grape.contact.subtitle': 'Entre em contato conosco para mais informações sobre disponibilidade, preços e especificações técnicas.',
        'grape.contact.cta': 'Solicitar Cotação',
        'seasonality.mini.title': 'Sazonalidade',
        'seasonality.high': 'Maior Disponibilidade',
        'seasonality.low': 'Menor Disponibilidade',
        'months.jan': 'Jan',
        'months.feb': 'Fev',
        'months.mar': 'Mar',
        'months.apr': 'Abr',
        'months.may': 'Mai',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Ago',
        'months.sep': 'Set',
        'months.oct': 'Out',
        'months.nov': 'Nov',
        'months.dec': 'Dez'
    },
    'en': {
        'grape.title': 'Grape',
        'grape.subtitle': 'Premium grapes from São Francisco Valley, internationally recognized for exceptional quality and flavor.',
        'grape.varieties.title': 'Varieties and Seasonality',
        'grape.varieties.intro': 'Each grape variety has unique characteristics and periods of greater availability throughout the year:',
        'grape.varieties.lumiar.title': 'BRS 54 Lumiar - Seedless',
        'grape.varieties.taina.title': 'BRS Tainá - With seeds',
        'grape.varieties.vitoria.title': 'BRS Vitória',
        'grape.varieties.magna.title': 'BRS Magna',
        'grape.varieties.iris.title': 'BRS Iris',
        'grape.varieties.melodia.title': 'BRS Melodia',
        'grape.varieties.weight': 'Bunch weight:',
        'grape.varieties.brix': 'Brix:',
        'grape.varieties.type': 'Type:',
        'grape.varieties.white': 'White',
        'grape.varieties.black': 'Black',
        'grape.varieties.red': 'Red',
        'grape.regions.title': 'Main Producing Regions',
        'grape.regions.saofrancisco.title': 'São Francisco Valley',
        'grape.regions.saofrancisco.description': 'Main table grape production region for export in Brazil, internationally recognized for superior quality and advanced irrigation technology.',
        'grape.regions.petrolina': 'Main irrigated fruit farming hub of São Francisco Valley, recognized for excellence in table grape production.',
        'grape.regions.juazeiro': 'Technological innovation center in tropical viticulture, with advanced irrigation and management technology.',
        'grape.commercialization.title': 'Commercialization',
        'grape.commercialization.punnets.title': 'Punnets',
        'grape.commercialization.bags.title': 'Bags',
        'grape.commercialization.pallet.title': 'Pallet',
        'grape.commercialization.pallet.air': 'Air:',
        'grape.commercialization.pallet.sea': 'Sea:',
        'grape.contact.title': 'Interested in Grapes?',
        'grape.contact.subtitle': 'Contact us for more information about availability, prices and technical specifications.',
        'grape.contact.cta': 'Request Quote',
        'seasonality.mini.title': 'Seasonality',
        'seasonality.high': 'Higher Availability',
        'seasonality.low': 'Lower Availability',
        'months.jan': 'Jan',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Apr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Aug',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dec'
    },
    'es': {
        'grape.title': 'Uva',
        'grape.subtitle': 'Uvas premium del Valle de São Francisco, reconocidas internacionalmente por calidad y sabor excepcionales.',
        'grape.varieties.title': 'Variedades y Estacionalidad',
        'grape.varieties.intro': 'Cada variedad de uva tiene características únicas y períodos de mayor disponibilidad a lo largo del año:',
        'grape.varieties.lumiar.title': 'BRS 54 Lumiar - Sin semillas',
        'grape.varieties.taina.title': 'BRS Tainá - Con semillas',
        'grape.varieties.vitoria.title': 'BRS Vitória',
        'grape.varieties.magna.title': 'BRS Magna',
        'grape.varieties.iris.title': 'BRS Iris',
        'grape.varieties.melodia.title': 'BRS Melodia',
        'grape.varieties.weight': 'Peso del racimo:',
        'grape.varieties.brix': 'Brix:',
        'grape.varieties.type': 'Tipo:',
        'grape.varieties.white': 'Blanca',
        'grape.varieties.black': 'Negra',
        'grape.varieties.red': 'Roja',
        'grape.regions.title': 'Principales Regiones Productoras',
        'grape.regions.saofrancisco.title': 'Valle de São Francisco',
        'grape.regions.saofrancisco.description': 'Principal región productora de uvas de mesa para exportación en Brasil, reconocida internacionalmente por calidad superior y tecnología de riego avanzada.',
        'grape.regions.petrolina': 'Principal polo de fruticultura irrigada del Valle de São Francisco, reconocido por la excelencia en producción de uvas de mesa.',
        'grape.regions.juazeiro': 'Centro de innovación tecnológica en viticultura tropical, con tecnología avanzada de riego y manejo.',
        'grape.commercialization.title': 'Comercialización',
        'grape.commercialization.punnets.title': 'Punnets',
        'grape.commercialization.bags.title': 'Bolsas',
        'grape.commercialization.pallet.title': 'Pallet',
        'grape.commercialization.pallet.air': 'Aéreo:',
        'grape.commercialization.pallet.sea': 'Marítimo:',
        'grape.contact.title': '¿Interesado en Uvas?',
        'grape.contact.subtitle': 'Contáctenos para más información sobre disponibilidad, precios y especificaciones técnicas.',
        'grape.contact.cta': 'Solicitar Cotización',
        'seasonality.mini.title': 'Estacionalidad',
        'seasonality.high': 'Mayor Disponibilidad',
        'seasonality.low': 'Menor Disponibilidad',
        'months.jan': 'Ene',
        'months.feb': 'Feb',
        'months.mar': 'Mar',
        'months.apr': 'Abr',
        'months.may': 'May',
        'months.jun': 'Jun',
        'months.jul': 'Jul',
        'months.aug': 'Ago',
        'months.sep': 'Sep',
        'months.oct': 'Oct',
        'months.nov': 'Nov',
        'months.dec': 'Dic'
    }
};

// Extend main translations with grape specific ones
if (typeof translations !== 'undefined') {
    Object.keys(grapeTranslations).forEach(lang => {
        if (translations[lang]) {
            Object.assign(translations[lang], grapeTranslations[lang]);
        }
    });
}

// Initialize Lucide icons when DOM is ready
document.addEventListener('DOMContentLoaded', function() {
    // Inicializar ícones Lucide
    if (window.lucide && typeof window.lucide.createIcons === 'function') {
        window.lucide.createIcons();
    }
});
